# the location of the file with the logged keystrokes
log_file_path: /Users/nathanfarmer/keystroke_analysis/keystrokes.log
# keyboard percentage for the logged keystrokes
input_key_set: 75
# do you want the parser to consider multiple presses and holding down keys
# as they are recorded (true) or as one keystroke (false)
count_multipresses: true
# number of categories to scale the results to
scale_categories: 10

